package com.objectif.onu.insarag_webapp.model;
// Generated 20-Jan-2019 19:43:36 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alerte generated by hbm2java
 */
public class Alerte implements java.io.Serializable {

	private int idalerte;
	private String entete;
	private Date dateDebut;
	private Date dateFin;
	private String infosSupp;
	private String pays;
	private String ville;
	private Set<Users> userses = new HashSet<Users>(0);

	public Alerte() {
	}

	public Alerte(int idalerte) {
		this.idalerte = idalerte;
	}

	public Alerte(int idalerte, String entete, Date dateDebut, Date dateFin, String infosSupp, String pays,
			String ville, Set<Users> userses) {
		this.idalerte = idalerte;
		this.entete = entete;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.infosSupp = infosSupp;
		this.pays = pays;
		this.ville = ville;
		this.userses = userses;
	}

	public int getIdalerte() {
		return this.idalerte;
	}

	public void setIdalerte(int idalerte) {
		this.idalerte = idalerte;
	}

	public String getEntete() {
		return this.entete;
	}

	public void setEntete(String entete) {
		this.entete = entete;
	}

	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	public String getInfosSupp() {
		return this.infosSupp;
	}

	public void setInfosSupp(String infosSupp) {
		this.infosSupp = infosSupp;
	}

	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
