package com.objectif.onu.insarag_webapp.model;
// Generated 10-Feb-2019 17:05:31 by Hibernate Tools 5.3.0.Beta2

/**
 * Arepondu generated by hbm2java
 */
public class Arepondu implements java.io.Serializable {

	private AreponduId id;
	private Alerte alerte;
	private Users users;

	public Arepondu() {
	}

	public Arepondu(AreponduId id, Alerte alerte, Users users) {
		this.id = id;
		this.alerte = alerte;
		this.users = users;
	}

	public AreponduId getId() {
		return this.id;
	}

	public void setId(AreponduId id) {
		this.id = id;
	}

	public Alerte getAlerte() {
		return this.alerte;
	}

	public void setAlerte(Alerte alerte) {
		this.alerte = alerte;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
