package com.objectif.onu.insarag_webapp.model;
// Generated 19-Feb-2019 14:21:18 by Hibernate Tools 5.3.0.Beta2

/**
 * AreponduId generated by hbm2java
 */
public class AreponduId implements java.io.Serializable {

	private int idAlerte;
	private int idUser;

	public AreponduId() {
	}

	public AreponduId(int idAlerte, int idUser) {
		this.idAlerte = idAlerte;
		this.idUser = idUser;
	}

	public int getIdAlerte() {
		return this.idAlerte;
	}

	public void setIdAlerte(int idAlerte) {
		this.idAlerte = idAlerte;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreponduId))
			return false;
		AreponduId castOther = (AreponduId) other;

		return (this.getIdAlerte() == castOther.getIdAlerte()) && (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlerte();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
