package com.objectif.onu.insarag_webapp.model;
// Generated 13-Jan-2019 14:59:36 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private int idGrade;
	private String libelle;
	private Set<Users> userses = new HashSet<Users>(0);

	public Grade() {
	}

	public Grade(int idGrade, String libelle) {
		this.idGrade = idGrade;
		this.libelle = libelle;
	}

	public Grade(int idGrade, String libelle, Set<Users> userses) {
		this.idGrade = idGrade;
		this.libelle = libelle;
		this.userses = userses;
	}

	public int getIdGrade() {
		return this.idGrade;
	}

	public void setIdGrade(int idGrade) {
		this.idGrade = idGrade;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
