package com.objectif.onu.insarag_webapp.model;
// Generated 19-Mar-2019 16:05:44 by Hibernate Tools 5.3.0.Beta2

/**
 * Infomission generated by hbm2java
 */
public class Infomission implements java.io.Serializable {

	private Integer idinfoMission;
	private int idMission;
	private String detailMission;

	public Infomission() {
	}

	public Infomission(int idMission) {
		this.idMission = idMission;
	}

	public Infomission(int idMission, String detailMission) {
		this.idMission = idMission;
		this.detailMission = detailMission;
	}

	public Integer getIdinfoMission() {
		return this.idinfoMission;
	}

	public void setIdinfoMission(Integer idinfoMission) {
		this.idinfoMission = idinfoMission;
	}

	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

	public String getDetailMission() {
		return this.detailMission;
	}

	public void setDetailMission(String detailMission) {
		this.detailMission = detailMission;
	}

}
