package com.objectif.onu.insarag_webapp.model;
// Generated 10-Feb-2019 17:05:31 by Hibernate Tools 5.3.0.Beta2

/**
 * Infomission generated by hbm2java
 */
public class Infomission implements java.io.Serializable {

	private int idinfoMission;
	private int idMission;
	private String detailMission;

	public Infomission() {
	}

	public Infomission(int idinfoMission, int idMission) {
		this.idinfoMission = idinfoMission;
		this.idMission = idMission;
	}

	public Infomission(int idinfoMission, int idMission, String detailMission) {
		this.idinfoMission = idinfoMission;
		this.idMission = idMission;
		this.detailMission = detailMission;
	}

	public int getIdinfoMission() {
		return this.idinfoMission;
	}

	public void setIdinfoMission(int idinfoMission) {
		this.idinfoMission = idinfoMission;
	}

	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

	public String getDetailMission() {
		return this.detailMission;
	}

	public void setDetailMission(String detailMission) {
		this.detailMission = detailMission;
	}

}
