package com.objectif.onu.insarag_webapp.model;
// Generated 19-Feb-2019 14:21:18 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Liensutiles generated by hbm2java
 */
public class Liensutiles implements java.io.Serializable {

	private int idliensutiles;
	private Mission mission;
	private String intitule;
	private String contenu;
	private Date date;
	private Byte isLink;

	public Liensutiles() {
	}

	public Liensutiles(int idliensutiles, Mission mission) {
		this.idliensutiles = idliensutiles;
		this.mission = mission;
	}

	public Liensutiles(int idliensutiles, Mission mission, String intitule, String contenu, Date date, Byte isLink) {
		this.idliensutiles = idliensutiles;
		this.mission = mission;
		this.intitule = intitule;
		this.contenu = contenu;
		this.date = date;
		this.isLink = isLink;
	}

	public int getIdliensutiles() {
		return this.idliensutiles;
	}

	public void setIdliensutiles(int idliensutiles) {
		this.idliensutiles = idliensutiles;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Byte getIsLink() {
		return this.isLink;
	}

	public void setIsLink(Byte isLink) {
		this.isLink = isLink;
	}

}
