package com.objectif.onu.insarag_webapp.model;
// Generated 10-Feb-2019 17:05:31 by Hibernate Tools 5.3.0.Beta2

/**
 * Mission generated by hbm2java
 */
public class Mission implements java.io.Serializable {

	private int idmission;
	private Alerte alerte;

	public Mission() {
	}

	public Mission(int idmission, Alerte alerte) {
		this.idmission = idmission;
		this.alerte = alerte;
	}

	public int getIdmission() {
		return this.idmission;
	}

	public void setIdmission(int idmission) {
		this.idmission = idmission;
	}

	public Alerte getAlerte() {
		return this.alerte;
	}

	public void setAlerte(Alerte alerte) {
		this.alerte = alerte;
	}

}
