package com.objectif.onu.insarag_webapp.model;
// Generated 19-Mar-2019 16:05:44 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays implements java.io.Serializable {

	private Integer idpays;
	private String nompays;
	private Set villes = new HashSet(0);

	public Pays() {
	}

	public Pays(String nompays) {
		this.nompays = nompays;
	}

	public Pays(String nompays, Set villes) {
		this.nompays = nompays;
		this.villes = villes;
	}

	public Integer getIdpays() {
		return this.idpays;
	}

	public void setIdpays(Integer idpays) {
		this.idpays = idpays;
	}

	public String getNompays() {
		return this.nompays;
	}

	public void setNompays(String nompays) {
		this.nompays = nompays;
	}

	public Set getVilles() {
		return this.villes;
	}

	public void setVilles(Set villes) {
		this.villes = villes;
	}

}
