package com.objectif.onu.insarag_webapp.model;
// Generated 20-Jan-2019 19:43:36 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays implements java.io.Serializable {

	private int idpays;
	private String nompays;
	private Set<Ville> villes = new HashSet<Ville>(0);

	public Pays() {
	}

	public Pays(int idpays, String nompays) {
		this.idpays = idpays;
		this.nompays = nompays;
	}

	public Pays(int idpays, String nompays, Set<Ville> villes) {
		this.idpays = idpays;
		this.nompays = nompays;
		this.villes = villes;
	}

	public int getIdpays() {
		return this.idpays;
	}

	public void setIdpays(int idpays) {
		this.idpays = idpays;
	}

	public String getNompays() {
		return this.nompays;
	}

	public void setNompays(String nompays) {
		this.nompays = nompays;
	}

	public Set<Ville> getVilles() {
		return this.villes;
	}

	public void setVilles(Set<Ville> villes) {
		this.villes = villes;
	}

}
