package com.objectif.onu.insarag_webapp.model;
// Generated 19-Mar-2019 16:05:44 by Hibernate Tools 5.3.0.Beta2

/**
 * Pois generated by hbm2java
 */
public class Pois implements java.io.Serializable {

	private Integer idpois;
	private double lat;
	private double longi;
	private String info;
	private int idMission;

	public Pois() {
	}

	public Pois(double lat, double longi, int idMission) {
		this.lat = lat;
		this.longi = longi;
		this.idMission = idMission;
	}

	public Pois(double lat, double longi, String info, int idMission) {
		this.lat = lat;
		this.longi = longi;
		this.info = info;
		this.idMission = idMission;
	}

	public Integer getIdpois() {
		return this.idpois;
	}

	public void setIdpois(Integer idpois) {
		this.idpois = idpois;
	}

	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public double getLongi() {
		return this.longi;
	}

	public void setLongi(double longi) {
		this.longi = longi;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

}
