package com.objectif.onu.insarag_webapp.model;
// Generated 20-Jan-2019 19:43:36 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Postes generated by hbm2java
 */
public class Postes implements java.io.Serializable {

	private int idPoste;
	private String libelle;
	private Set<Users> userses = new HashSet<Users>(0);

	public Postes() {
	}

	public Postes(int idPoste) {
		this.idPoste = idPoste;
	}

	public Postes(int idPoste, String libelle, Set<Users> userses) {
		this.idPoste = idPoste;
		this.libelle = libelle;
		this.userses = userses;
	}

	public int getIdPoste() {
		return this.idPoste;
	}

	public void setIdPoste(int idPoste) {
		this.idPoste = idPoste;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
