package com.objectif.onu.insarag_webapp.model;
// Generated 19-Feb-2019 14:21:18 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Postes generated by hbm2java
 */
public class Postes implements java.io.Serializable {

	private int idPoste;
	private String libelle;
	private Set userses = new HashSet(0);

	public Postes() {
	}

	public Postes(int idPoste) {
		this.idPoste = idPoste;
	}

	public Postes(int idPoste, String libelle, Set userses) {
		this.idPoste = idPoste;
		this.libelle = libelle;
		this.userses = userses;
	}

	public int getIdPoste() {
		return this.idPoste;
	}

	public void setIdPoste(int idPoste) {
		this.idPoste = idPoste;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
