package com.objectif.onu.insarag_webapp.model;
// Generated 03-Jan-2019 17:58:35 by Hibernate Tools 5.3.0.Beta2

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private int id;
	private Users users;
	private String titre;

	public Roles() {
	}

	public Roles(int id, Users users) {
		this.id = id;
		this.users = users;
	}

	public Roles(int id, Users users, String titre) {
		this.id = id;
		this.users = users;
		this.titre = titre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

}
