package com.objectif.onu.insarag_webapp.model;
// Generated 19-Mar-2019 16:05:44 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idusers;
	private Grade grade;
	private Postes postes;
	private String email;
	private String password;
	private String telephone;
	private Byte enMission;
	private String nom;
	private String prenom;
	private Set arepondus = new HashSet(0);
	private Set roleses = new HashSet(0);

	public Users() {
	}

	public Users(Grade grade, Postes postes, String email, String password, String nom, String prenom) {
		this.grade = grade;
		this.postes = postes;
		this.email = email;
		this.password = password;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Users(Grade grade, Postes postes, String email, String password, String telephone, Byte enMission,
			String nom, String prenom, Set arepondus, Set roleses) {
		this.grade = grade;
		this.postes = postes;
		this.email = email;
		this.password = password;
		this.telephone = telephone;
		this.enMission = enMission;
		this.nom = nom;
		this.prenom = prenom;
		this.arepondus = arepondus;
		this.roleses = roleses;
	}

	public Integer getIdusers() {
		return this.idusers;
	}

	public void setIdusers(Integer idusers) {
		this.idusers = idusers;
	}

	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	public Postes getPostes() {
		return this.postes;
	}

	public void setPostes(Postes postes) {
		this.postes = postes;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Byte getEnMission() {
		return this.enMission;
	}

	public void setEnMission(Byte enMission) {
		this.enMission = enMission;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Set getArepondus() {
		return this.arepondus;
	}

	public void setArepondus(Set arepondus) {
		this.arepondus = arepondus;
	}

	public Set getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set roleses) {
		this.roleses = roleses;
	}

}
