package com.objectif.onu.insarag_webapp.model;
// Generated 03-Jan-2019 17:58:35 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int idusers;
	private String userName;
	private String password;
	private Set roleses = new HashSet(0);

	public Users() {
	}

	public Users(int idusers) {
		this.idusers = idusers;
	}

	public Users(int idusers, String userName, String password, Set roleses) {
		this.idusers = idusers;
		this.userName = userName;
		this.password = password;
		this.roleses = roleses;
	}

	public int getIdusers() {
		return this.idusers;
	}

	public void setIdusers(int idusers) {
		this.idusers = idusers;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set roleses) {
		this.roleses = roleses;
	}

}
