package com.objectif.onu.insarag_webapp.model;
// Generated 19-Mar-2019 16:05:44 by Hibernate Tools 5.3.0.Beta2

/**
 * Ville generated by hbm2java
 */
public class Ville implements java.io.Serializable {

	private Integer idville;
	private Pays pays;
	private String nomville;

	public Ville() {
	}

	public Ville(Pays pays, String nomville) {
		this.pays = pays;
		this.nomville = nomville;
	}

	public Integer getIdville() {
		return this.idville;
	}

	public void setIdville(Integer idville) {
		this.idville = idville;
	}

	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	public String getNomville() {
		return this.nomville;
	}

	public void setNomville(String nomville) {
		this.nomville = nomville;
	}

}
