package com.objectif.onu.insarag_webapp.model;
// Generated 20-Jan-2019 19:43:36 by Hibernate Tools 5.0.6.Final

/**
 * Ville generated by hbm2java
 */
public class Ville implements java.io.Serializable {

	private int idville;
	private Pays pays;
	private String nomville;

	public Ville() {
	}

	public Ville(int idville, Pays pays, String nomville) {
		this.idville = idville;
		this.pays = pays;
		this.nomville = nomville;
	}

	public int getIdville() {
		return this.idville;
	}

	public void setIdville(int idville) {
		this.idville = idville;
	}

	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	public String getNomville() {
		return this.nomville;
	}

	public void setNomville(String nomville) {
		this.nomville = nomville;
	}

}
