-- MySQL Script generated by MySQL Workbench
-- Sun Jan 13 15:28:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema insarag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema insarag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insarag` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `insarag` ;

-- -----------------------------------------------------
-- Table `insarag`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insarag`.`grade` (
  `idGrade` INT(11) NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrade`),
  UNIQUE INDEX `libelle_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insarag`.`postes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insarag`.`postes` (
  `idPoste` INT(11) NOT NULL,
  `libelle` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPoste`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insarag`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insarag`.`users` (
  `idusers` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `idGrade` INT(11) NOT NULL,
  `enMission` TINYINT(4) NULL DEFAULT '0',
  `idPoste` INT(11) NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `userName_UNIQUE` (`email` ASC),
  INDEX `idGrade_idx` (`idGrade` ASC),
  INDEX `fk_poste_idx` (`idPoste` ASC),
  CONSTRAINT `fk_grade`
    FOREIGN KEY (`idGrade`)
    REFERENCES `insarag`.`grade` (`idGrade`),
  CONSTRAINT `fk_poste`
    FOREIGN KEY (`idPoste`)
    REFERENCES `insarag`.`postes` (`idPoste`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insarag`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insarag`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL DEFAULT NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  INDEX `fk_user_idx` (`user` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user`)
    REFERENCES `insarag`.`users` (`idusers`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
